spring.application.name=croop

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/CROOP
spring.datasource.username=researcher_authors
spring.datasource.password=croop_2105

# PostgreSQL Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# Connection Pooling (HikariCP)
spring.datasource.hikari.maximum-pool-size=10

# Hibernate Configuration
spring.jpa.database=postgresql
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

server.port=8081

