spring.application.name=croop

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://aws-0-ap-southeast-1.pooler.supabase.com:5432/postgres?user=postgres.qgydjvkbsuwqmtchemgo&password=RedPutation1989
spring.datasource.sslmode=require


# PostgreSQL Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# Connection Pooling (HikariCP)
spring.datasource.hikari.maximum-pool-size=10

# Hibernate Configuration
spring.jpa.database=postgresql
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

server.port=8081

